import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SortingAlgorithmProvider } from '@/context/visualizer-context';
import { cn } from '@/lib/utils';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={cn('text-gray-300', inter.className)}>
                <SortingAlgorithmProvider>{children}</SortingAlgorithmProvider>
            </body>
        </html>
    );
}
